#!groovy

// Generated by IBM TransformationAdvisor
// Thu Mar 28 19:13:33 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}